version: '3.5'

services:
  kafka-cluster:
    container_name: kafka_container1
    image: landoop/fast-data-dev:cp3.3.0
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0                 # Disable Running tests
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
      - 9092:9092                 # Kafka Broker

  postgres:
    container_name: postgres_container1
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password #todo security
      POSTGRES_DB: vt_db
    ports:
      - "5432:5432"

  hh-loader:
    image: hh-loader
    network_mode: host #todo security
    depends_on:
      - postgres
      - kafka-cluster

  flink-loader:
    image: flink-loader
    network_mode: host #todo security
    depends_on:
      - postgres
      - kafka-cluster
      - hh-loader
